In [1]:
import requests
import simplejson as json
import pandas as pd  # for DataFrame creation and manipulation
import numpy as np   # np is convention for easy calling
import matplotlib.pyplot as plt  # for plotting
import os    # pythons operating system for loading/saving files
from pandas.io.json import json_normalize
from bokeh.io import push_notebook, show, output_notebook
from bokeh.layouts import row
from bokeh.plotting import figure

api_key = '5eWyXUgyDyNbYXctVW53'  # static value
start_date = '2013-01-01'    # needs to be user defined
end_date = '2017-06-11'      # needs to be user defined
ticker = 'FB'                # needs to be user defined
api_url = "https://www.quandl.com/api/v3/datasets/WIKI/%s/data.json" % ticker
payload = {'api_key': api_key, 'start_date': start_date, 'end_date': end_date, 'order': 'asc'}
r = requests.get(api_url, params = payload)
r_raw = r.json()   
json_normalize(r_raw)    # Normalize JSON object into flat table
r_cols = r_raw['dataset_data']['column_names']  # Extract column names
r_data = r_raw['dataset_data']['data']   # Extract data

numdays = 3     # needs to measure length
df = pd.DataFrame(r_data)
df.columns = r_cols
df  # print result

,Date,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
0,2013-01-02,27.440,28.1800,27.4200,28.0000,69846400.0,0.0,1.0,27.440,28.1800,27.4200,28.0000,69846400.0
1,2013-01-03,27.880,28.4700,27.5900,27.7700,63140600.0,0.0,1.0,27.880,28.4700,27.5900,27.7700,63140600.0
2,2013-01-04,28.010,28.9300,27.8300,28.7600,72715400.0,0.0,1.0,28.010,28.9300,27.8300,28.7600,72715400.0
3,2013-01-07,28.690,29.7900,28.6500,29.4213,83781800.0,0.0,1.0,28.690,29.7900,28.6500,29.4213,83781800.0
4,2013-01-08,29.510,29.6000,28.8600,29.0607,45871300.0,0.0,1.0,29.510,29.6000,28.8600,29.0607,45871300.0
5,2013-01-09,29.670,30.6000,29.4900,30.5900,104787700.0,0.0,1.0,29.670,30.6000,29.4900,30.5900,104787700.0
6,2013-01-10,30.600,31.4500,30.2800,31.3000,95316400.0,0.0,1.0,30.600,31.4500,30.2800,31.3000,95316400.0
7,2013-01-11,31.280,31.9600,31.1000,31.7200,89598000.0,0.0,1.0,31.280,31.9600,31.1000,31.7200,89598000.0
8,2013-01-14,32.080,32.2100,30.6200,30.9475,98892800.0,0.0,1.0,32.080,32.2100,30.6200,30.9475,98892800.0
9,2013-01-15,30.640,31.7100,29.8800,30.1000,173242600.0,0.0,1.0,30.640,31.7100,29.8800,30.1000,173242600.0
10,2013-01-16,30.210,30.3500,29.5300,29.8500,75332700.0,0.0,1.0,30.210,30.3500,29.5300,29.8500,75332700.0
11,2013-01-17,30.080,30.4200,30.0300,30.1400,40256700.0,0.0,1.0,30.080,30.4200,30.0300,30.1400,40256700.0
12,2013-01-18,30.310,30.4400,29.2700,29.6600,49631500.0,0.0,1.0,30.310,30.4400,29.2700,29.6600,49631500.0
13,2013-01-22,29.750,30.8900,29.7400,30.7290,55243300.0,0.0,1.0,29.750,30.8900,29.7400,30.7290,55243300.0
14,2013-01-23,31.100,31.5000,30.8000,30.8200,48899800.0,0.0,1.0,31.100,31.5000,30.8000,30.8200,48899800.0
15,2013-01-24,31.270,31.4900,30.8100,31.0800,43845100.0,0.0,1.0,31.270,31.4900,30.8100,31.0800,43845100.0
16,2013-01-25,31.410,31.9300,31.1300,31.5400,54363600.0,0.0,1.0,31.410,31.9300,31.1300,31.5400,54363600.0
17,2013-01-28,31.880,32.5063,31.8100,32.4690,59682500.0,0.0,1.0,31.880,32.5063,31.8100,32.4690,59682500.0
18,2013-01-29,32.000,32.0700,30.7100,30.7900,72976500.0,0.0,1.0,32.000,32.0700,30.7100,30.7900,72976500.0
19,2013-01-30,30.980,31.4900,30.8800,31.2400,87682100.0,0.0,1.0,30.980,31.4900,30.8800,31.2400,87682100.0
20,2013-01-31,29.150,31.4700,28.7400,30.9810,190744900.0,0.0,1.0,29.150,31.4700,28.7400,30.9810,190744900.0
21,2013-02-01,31.010,31.0200,29.6300,29.7300,85856700.0,0.0,1.0,31.010,31.0200,29.6300,29.7300,85856700.0
22,2013-02-04,29.060,29.2000,28.0100,28.1090,92362200.0,0.0,1.0,29.060,29.2000,28.0100,28.1090,92362200.0
23,2013-02-05,28.260,28.9600,28.0400,28.6400,47948200.0,0.0,1.0,28.260,28.9600,28.0400,28.6400,47948200.0
24,2013-02-06,28.740,29.2900,28.6600,29.0500,38375900.0,0.0,1.0,28.740,29.2900,28.6600,29.0500,38375900.0
25,2013-02-07,29.110,29.1500,28.2700,28.6500,34540100.0,0.0,1.0,29.110,29.1500,28.2700,28.6500,34540100.0
26,2013-02-08,28.890,29.1700,28.5100,28.5450,37708800.0,0.0,1.0,28.890,29.1700,28.5100,28.5450,37708800.0
27,2013-02-11,28.610,28.6800,28.0400,28.2600,37361800.0,0.0,1.0,28.610,28.6800,28.0400,28.2600,37361800.0
28,2013-02-12,27.670,28.1600,27.1000,27.3700,93498700.0,0.0,1.0,27.670,28.1600,27.1000,27.3700,93498700.0
29,2013-02-13,27.360,28.3200,27.3100,27.9075,50164000.0,0.0,1.0,27.360,28.3200,27.3100,27.9075,50164000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,2017-04-28,149.500,151.5300,149.0700,150.2500,30280373.0,0.0,1.0,149.500,151.5300,149.0700,150.2500,30280373.0
1089,2017-05-01,151.740,152.5700,151.4200,152.4600,24669159.0,0.0,1.0,151.740,152.5700,151.4200,152.4600,24669159.0
1090,2017-05-02,153.340,153.4400,151.6600,152.7800,21255365.0,0.0,1.0,153.340,153.4400,151.6600,152.7800,21255365.0
1091,2017-05-03,153.600,153.6000,151.3400,151.8000,21755088.0,0.0,1.0,153.600,153.6000,151.3400,151.8000,21755088.0
1092,2017-05-04,150.170,151.5200,148.7200,150.8500,36060301.0,0.0,1.0,150.170,151.5200,148.7200,150.8500,36060301.0
1093,2017-05-05,151.450,151.6300,149.7900,150.2400,17051519.0,0.0,1.0,151.450,151.6300,149.7900,150.2400,17051519.0
1094,2017-05-08,150.710,151.0800,149.7400,151.0600,15662472.0,0.0,1.0,150.710,151.0800,149.7400,151.0600,15662472.0
1095,2017-05-09,151.490,152.5900,150.2100,150.4800,17325999.0,0.0,1.0,151.490,152.5900,150.2100,150.4800,17325999.0
1096,2017-05-10,150.230,150.5200,148.8600,150.2900,11653395.0,0.0,1.0,150.230,150.5200,148.8600,150.2900,11653395.0
1097,2017-05-11,150.310,150.6500,149.4100,150.0400,11623865.0,0.0,1.0,150.310,150.6500,149.4100,150.0400,11623865.0
1098,2017-05-12,150.400,150.4600,149.6300,150.3300,9497040.0,0.0,1.0,150.400,150.4600,149.6300,150.3300,9497040.0
1099,2017-05-15,150.170,151.4800,149.7700,150.1900,14909882.0,0.0,1.0,150.170,151.4800,149.7700,150.1900,14909882.0
1100,2017-05-16,150.110,150.2100,149.0300,149.7800,14420715.0,0.0,1.0,150.110,150.2100,149.0300,149.7800,14420715.0
1101,2017-05-17,148.000,148.6700,144.4216,144.8500,27908167.0,0.0,1.0,148.000,148.6700,144.4216,144.8500,27908167.0
1102,2017-05-18,144.720,148.1500,144.5100,147.6600,21784326.0,0.0,1.0,144.720,148.1500,144.5100,147.6600,21784326.0
1103,2017-05-19,148.445,149.3900,147.9600,148.0600,16101229.0,0.0,1.0,148.445,149.3900,147.9600,148.0600,16101229.0
1104,2017-05-22,148.080,148.5900,147.6900,148.2400,12379481.0,0.0,1.0,148.080,148.5900,147.6900,148.2400,12379481.0
1105,2017-05-23,148.520,148.8100,147.2500,148.0700,12665886.0,0.0,1.0,148.520,148.8100,147.2500,148.0700,12665886.0
1106,2017-05-24,148.510,150.2300,148.4200,150.0400,17769670.0,0.0,1.0,148.510,150.2300,148.4200,150.0400,17769670.0
1107,2017-05-25,150.300,152.5900,149.9500,151.9600,19780399.0,0.0,1.0,150.300,152.5900,149.9500,151.9600,19780399.0
1108,2017-05-26,152.230,152.2500,151.1500,152.1300,14907827.0,0.0,1.0,152.230,152.2500,151.1500,152.1300,14907827.0
1109,2017-05-30,151.970,152.9000,151.6400,152.3800,13145329.0,0.0,1.0,151.970,152.9000,151.6400,152.3800,13145329.0
1110,2017-05-31,152.700,153.3500,151.0900,151.4600,17709427.0,0.0,1.0,152.700,153.3500,151.0900,151.4600,17709427.0
1111,2017-06-01,151.750,152.2900,150.3000,151.5300,14459173.0,0.0,1.0,151.750,152.2900,150.3000,151.5300,14459173.0
1112,2017-06-02,151.850,153.6300,151.3000,153.6100,16787255.0,0.0,1.0,151.850,153.6300,151.3000,153.6100,16787255.0
1113,2017-06-05,153.640,154.7088,153.4100,153.6300,12279871.0,0.0,1.0,153.640,154.7088,153.4100,153.6300,12279871.0
1114,2017-06-06,153.410,154.5200,152.4800,152.8100,13291727.0,0.0,1.0,153.410,154.5200,152.4800,152.8100,13291727.0
1115,2017-06-07,153.270,153.7500,152.3400,153.1200,11822136.0,0.0,1.0,153.270,153.7500,152.3400,153.1200,11822136.0
1116,2017-06-08,154.080,154.7300,153.1000,154.7100,17539521.0,0.0,1.0,154.080,154.7300,153.1000,154.7100,17539521.0
1117,2017-06-09,154.770,155.5900,146.6100,149.6300,35256368.0,0.0,1.0,154.770,155.5900,146.6100,149.6300,35256368.0

In [ ]:
from bokeh.layouts import gridplot
from bokeh.plotting import figure, show, output_file

def datetime(x):
    return np.array(x, dtype=np.datetime64)

closing_pr = True   #debug, can be removed
adj_closing_pr = True  #debug, can be removed
opening_pr = False    #debug, can be removed
adj_opening_pr = False  #debug, can be removed

output_notebook()
p1 = figure(x_axis_type="datetime", title="Data from Quandle WIKI set")
p1.grid.grid_line_alpha=0.3
p1.xaxis.axis_label = 'Date'
p1.yaxis.axis_label = 'Price'

if opening_pr:
    p1.line(datetime(df['Date']), df['Open'], color='#A6CEE3', legend= ticker+':Open')
if adj_opening_pr:
    p1.line(datetime(df['Date']), df['Adj. Open'], color='#B2DF8A', legend= ticker+':Adj. Open')
if closing_pr:
    p1.line(datetime(df['Date']), df['Close'], color='#33A02C', legend=ticker+':Close')
if adj_closing_pr:
    p1.line(datetime(df['Date']), df['Adj. Close'], color='#FB9A99', legend=ticker+': Adj. Close')
p1.legend.location = "top_left"

output_file("stocks.html", title="Stock_Info_Output", mode = 'relative',\
            root_dir= '/templates')

show(gridplot([[p1]], plot_width=400, plot_height=400))  # open a browser

In [ ]:
print([ticker,': c'])